export interface StreamingService {
  id: string;
  label: string;
}

export interface StreamingRegion {
  code: string;
  label: string;
  services: StreamingService[];
}

export const STREAMING_REGIONS: StreamingRegion[] = [
  {
    code: 'CA',
    label: 'Canada',
    services: [
      { id: 'netflix',    label: 'Netflix' },
      { id: 'prime',      label: 'Prime Video' },
      { id: 'crave',      label: 'Crave' },
      { id: 'disney',     label: 'Disney+' },
      { id: 'appletv',    label: 'Apple TV+' },
      { id: 'paramount',  label: 'Paramount+' },
      { id: 'hbomax',     label: 'HBO Max' },
      { id: 'tubi',       label: 'Tubi' },
      { id: 'plutotv',    label: 'Pluto TV' },
      { id: 'shudder',    label: 'Shudder' },
      { id: 'mubi',       label: 'MUBI' },
      { id: 'cbcgem',     label: 'CBC Gem' },
    ],
  },
  {
    code: 'US',
    label: 'United States',
    services: [
      { id: 'netflix',    label: 'Netflix' },
      { id: 'prime',      label: 'Prime Video' },
      { id: 'hbomax',     label: 'HBO Max' },
      { id: 'disney',     label: 'Disney+' },
      { id: 'appletv',    label: 'Apple TV+' },
      { id: 'paramount',  label: 'Paramount+' },
      { id: 'peacock',    label: 'Peacock' },
      { id: 'hulu',       label: 'Hulu' },
      { id: 'tubi',       label: 'Tubi' },
      { id: 'plutotv',    label: 'Pluto TV' },
      { id: 'shudder',    label: 'Shudder' },
      { id: 'mubi',       label: 'MUBI' },
      { id: 'amcplus',    label: 'AMC+' },
      { id: 'crunchyroll',label: 'Crunchyroll' },
    ],
  },
  {
    code: 'GB',
    label: 'United Kingdom',
    services: [
      { id: 'netflix',    label: 'Netflix' },
      { id: 'prime',      label: 'Prime Video' },
      { id: 'disney',     label: 'Disney+' },
      { id: 'appletv',    label: 'Apple TV+' },
      { id: 'bbciplayer', label: 'BBC iPlayer' },
      { id: 'itvx',       label: 'ITVX' },
      { id: 'channel4',   label: 'Channel 4' },
      { id: 'britbox',    label: 'BritBox' },
      { id: 'paramount',  label: 'Paramount+' },
      { id: 'nowtv',      label: 'NOW TV' },
      { id: 'shudder',    label: 'Shudder' },
      { id: 'mubi',       label: 'MUBI' },
      { id: 'crunchyroll',label: 'Crunchyroll' },
    ],
  },
  {
    code: 'AU',
    label: 'Australia',
    services: [
      { id: 'netflix',    label: 'Netflix' },
      { id: 'prime',      label: 'Prime Video' },
      { id: 'disney',     label: 'Disney+' },
      { id: 'appletv',    label: 'Apple TV+' },
      { id: 'binge',      label: 'Binge' },
      { id: 'stan',       label: 'Stan' },
      { id: 'foxtel',     label: 'Foxtel' },
      { id: 'paramount',  label: 'Paramount+' },
      { id: 'tubi',       label: 'Tubi' },
      { id: 'abciview',   label: 'ABC iview' },
      { id: 'sbsondemand',label: 'SBS On Demand' },
      { id: 'mubi',       label: 'MUBI' },
    ],
  },
  {
    code: 'FR',
    label: 'France',
    services: [
      { id: 'netflix',    label: 'Netflix' },
      { id: 'prime',      label: 'Prime Video' },
      { id: 'disney',     label: 'Disney+' },
      { id: 'appletv',    label: 'Apple TV+' },
      { id: 'canalplus',  label: 'Canal+' },
      { id: 'ocs',        label: 'OCS' },
      { id: 'salto',      label: 'Salto' },
      { id: 'mubi',       label: 'MUBI' },
      { id: 'crunchyroll',label: 'Crunchyroll' },
      { id: 'adn',        label: 'ADN' },
    ],
  },
  {
    code: 'DE',
    label: 'Germany',
    services: [
      { id: 'netflix',    label: 'Netflix' },
      { id: 'prime',      label: 'Prime Video' },
      { id: 'disney',     label: 'Disney+' },
      { id: 'appletv',    label: 'Apple TV+' },
      { id: 'rtlplus',    label: 'RTL+' },
      { id: 'joyn',       label: 'Joyn' },
      { id: 'mubi',       label: 'MUBI' },
      { id: 'crunchyroll',label: 'Crunchyroll' },
      { id: 'wow',        label: 'WOW' },
      { id: 'skygo',      label: 'Sky Go' },
    ],
  },
  {
    code: 'JP',
    label: 'Japan',
    services: [
      { id: 'netflix',    label: 'Netflix' },
      { id: 'prime',      label: 'Prime Video' },
      { id: 'disney',     label: 'Disney+' },
      { id: 'appletv',    label: 'Apple TV+' },
      { id: 'hulujp',     label: 'Hulu Japan' },
      { id: 'unext',      label: 'U-NEXT' },
      { id: 'dazn',       label: 'DAZN' },
      { id: 'crunchyroll',label: 'Crunchyroll' },
      { id: 'abema',      label: 'Abema' },
      { id: 'nhkplus',    label: 'NHK+' },
    ],
  },
  {
    code: 'MX',
    label: 'Mexico',
    services: [
      { id: 'netflix',    label: 'Netflix' },
      { id: 'prime',      label: 'Prime Video' },
      { id: 'disney',     label: 'Disney+' },
      { id: 'appletv',    label: 'Apple TV+' },
      { id: 'paramount',  label: 'Paramount+' },
      { id: 'blimtv',     label: 'Blim TV' },
      { id: 'clarovideo', label: 'Claro Video' },
      { id: 'crunchyroll',label: 'Crunchyroll' },
      { id: 'mubi',       label: 'MUBI' },
    ],
  },
  {
    code: 'BR',
    label: 'Brazil',
    services: [
      { id: 'netflix',    label: 'Netflix' },
      { id: 'prime',      label: 'Prime Video' },
      { id: 'disney',     label: 'Disney+' },
      { id: 'appletv',    label: 'Apple TV+' },
      { id: 'paramount',  label: 'Paramount+' },
      { id: 'globoplay',  label: 'Globoplay' },
      { id: 'crunchyroll',label: 'Crunchyroll' },
      { id: 'mubi',       label: 'MUBI' },
      { id: 'starplus',   label: 'Star+' },
    ],
  },
  {
    code: 'IN',
    label: 'India',
    services: [
      { id: 'netflix',      label: 'Netflix' },
      { id: 'prime',        label: 'Prime Video' },
      { id: 'disneyhotstar',label: 'Disney+ Hotstar' },
      { id: 'appletv',      label: 'Apple TV+' },
      { id: 'jiocinema',    label: 'JioCinema' },
      { id: 'sonyliv',      label: 'SonyLIV' },
      { id: 'zee5',         label: 'ZEE5' },
      { id: 'aha',          label: 'Aha' },
      { id: 'mxplayer',     label: 'MX Player' },
      { id: 'crunchyroll',  label: 'Crunchyroll' },
    ],
  },
];
